# Generated by Django 4.2.4 on 2023-08-03 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('climate', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 3, 1, 3, 42, 949202, tzinfo=datetime.timezone.utc))),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gravity', models.IntegerField()),
                ('population', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthYear', models.CharField(max_length=20)),
                ('eyeColor', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('hairColor', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='main.planet')),
            ],
        ),
    ]
